<?php if(!defined('ABSPATH'))exit; ?>
<meta charset="<?php bloginfo('charset'); ?>">
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="preload" as="font" type="font/woff2" href="/wp-content/hw-fonts/f5.woff2" crossorigin>
<style id="hw-critical">:root{--red:#e01f30;--red-h:#dd3333}*{box-sizing:border-box}body.hw-page{margin:0;font-family:"Open Sans",Helvetica,Arial,sans-serif;color:#2d2d2d;overflow-x:hidden;padding-top:122px;background:#efefef}.hw-wrap{width:100%;max-width:1236px;margin:0 auto;padding:0 30px}img{max-width:100%}#hw-header{position:fixed;top:0;left:0;right:0;z-index:99999}.hw-topbar{background:#444;height:47px;display:flex;align-items:center}.hw-topbar .hw-wrap{display:flex;align-items:center;justify-content:flex-start;gap:26px}.hw-topbar .hw-phone,.hw-topbar .hw-email{font-family:ABeeZee,Helvetica,Arial,sans-serif;font-size:18px;line-height:18px;color:#fff;text-decoration:none;display:inline-flex;align-items:center;gap:8px}.hw-topbar .hw-phone{font-weight:600}.hw-topbar .hw-email{font-weight:700}.hw-mainbar{background:#000;height:75px;display:flex;align-items:center}.hw-mainbar .hw-wrap{display:flex;align-items:flex-end;justify-content:space-between;height:75px}.hw-logo{display:flex;align-items:center;align-self:center;margin-left:4px}.hw-logo img{height:53px;width:auto;display:block}.hw-nav{display:flex;align-items:flex-end;gap:24px}.hw-nav ul{display:flex;align-items:flex-end;gap:22px;list-style:none;margin:0;padding:0}.hw-nav ul a{font-family:Poppins,Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:40px;color:#fff;text-decoration:none;text-transform:uppercase;display:inline-flex;align-items:center;gap:6px;white-space:nowrap;padding:0 10px}.hw-caret{display:inline-block;width:0;height:0;border-left:4px solid transparent;border-right:4px solid transparent;border-top:5px solid currentColor;opacity:.85}.hw-reserve{font-family:Poppins,Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:16px;color:#fff;text-decoration:none;text-transform:uppercase;background:var(--red);padding:12px 18px;border-radius:4px;display:inline-flex;align-items:center;gap:8px;white-space:nowrap}.hw-burger{display:none;flex-direction:column;justify-content:center;gap:5px;width:56px;height:44px;padding:0 13px;background:#4a4a4a;border:0;border-radius:6px;cursor:pointer}.hw-burger span{display:block;height:3px;width:100%;background:#fff;border-radius:2px}.hw-mobmenu{display:none}
/* ==== Category listing components ==== */
.hw-cat-sec{padding:57px 0 0}.hw-cat-title{font-family:Poppins,Helvetica,Arial,sans-serif;font-weight:700;font-size:50px;line-height:50px;color:var(--red);text-align:center;margin:0 0 24px}.hw-cat-sub{font-family:Poppins,Helvetica,Arial,sans-serif;font-weight:600;font-size:30px;line-height:1.25;color:#333;text-align:center;margin:0 0 16px}.hw-cat-intro{font-family:Roboto,Helvetica,Arial,sans-serif;font-weight:500;font-size:20px;line-height:36px;color:#000;text-align:center;max-width:1010px;margin:0 auto}.hw-cat-intro+.hw-cat-intro{margin-top:20px}
.hw-band{background:var(--red);padding:46px 0;margin-top:44px}.hw-band+.hw-band{margin-top:0}.hw-band-gray{background:#606060}.hw-band-title{font-family:Poppins,Helvetica,Arial,sans-serif;font-weight:700;font-size:35px;line-height:35px;color:#fff;text-align:center;margin:0 0 28px}.hw-band-cols{display:grid;grid-template-columns:repeat(3,1fr);gap:0}.hw-band-cols ul{list-style:disc;margin:0;padding:0 0 0 34px}.hw-band-cols li{font-family:Roboto,Helvetica,Arial,sans-serif;font-weight:500;font-size:20px;line-height:26px;color:#fff}
.hw-cat-gridsec{padding:57px 0}.hw-cat-grid{display:grid;grid-template-columns:repeat(3,1fr);column-gap:35px;row-gap:57px}.hw-cat-card{text-align:left}.hw-cat-card-img{display:block;line-height:0;margin:0 0 17px}.hw-cat-card-img img{width:100%;object-fit:cover;display:block;box-shadow:0 6px 16px rgba(0,0,0,.14)}.hw-cat-card-title{font-family:Poppins,Helvetica,Arial,sans-serif;font-weight:600;font-size:20px;line-height:28px;color:#000;margin:0 0 8px}.hw-cat-card-desc{font-family:Roboto,Helvetica,Arial,sans-serif;font-weight:300;font-size:15px;line-height:27px;color:#000;margin:0 0 18px}.hw-btn-red{font-family:Poppins,Helvetica,Arial,sans-serif;font-weight:500;font-size:14px;line-height:24px;letter-spacing:1px;text-transform:uppercase;color:#fff;background:var(--red);padding:10px;display:inline-block;text-decoration:none}
.hw-cat-links{margin:8px 0 0}.hw-cat-links p{font-family:Roboto,Helvetica,Arial,sans-serif;font-weight:400;font-size:14px;line-height:1.9;color:#000;margin:0}.hw-cat-links a{color:var(--red);font-weight:700;text-decoration:none;word-break:break-word}
.hw-storehero{background:#333 center/cover no-repeat;min-height:470px;display:flex;align-items:center;justify-content:center;text-align:center;padding:60px 20px}.hw-storehero-in{max-width:780px}.hw-storehero h2{font-family:Poppins,Helvetica,Arial,sans-serif;font-weight:700;font-size:50px;line-height:1.15;color:#fff;text-transform:uppercase;margin:0 0 18px;text-shadow:0 1px 3px rgba(0,0,0,.4)}.hw-storehero p{font-family:Poppins,Helvetica,Arial,sans-serif;font-weight:600;font-size:18px;line-height:1.5;color:#fff;margin:0 0 26px;text-shadow:0 1px 3px rgba(0,0,0,.4)}.hw-storehero .hw-btn-red{font-size:15px;padding:13px 26px}
/* ==== Spec / gallery pages (archetype 2) ==== */
.hw-hero-full{width:100%;aspect-ratio:1440/678;background-position:center;background-size:cover;background-repeat:no-repeat}
.hw-redband{background:var(--red);padding:42px 20px;text-align:center}.hw-redband-title{font-family:Poppins,Helvetica,Arial,sans-serif;font-weight:600;font-size:36px;line-height:1.2;color:#fff;margin:0}.hw-redband-title+.hw-redband-text{margin-top:14px}.hw-redband-text{font-family:Roboto,Helvetica,Arial,sans-serif;font-weight:500;font-size:20px;line-height:1.5;color:#fff;margin:0 auto;max-width:1040px}
.hw-split{display:grid;grid-template-columns:1fr 1fr}.hw-split+.hw-split{margin-top:40px}.hw-split-img{background-position:center;background-size:cover;background-repeat:no-repeat;min-height:470px}.hw-split-body{background:#efefef;padding:52px 60px;display:flex;flex-direction:column;justify-content:center}.hw-split-body.wide{padding:52px 70px}
.hw-spec-h{font-family:Poppins,Helvetica,Arial,sans-serif;font-weight:600;font-size:30px;line-height:1.25;color:#333;margin:0 0 18px}.hw-spec-h2{font-family:"Open Sans",Helvetica,Arial,sans-serif;font-weight:700;font-size:17px;line-height:1.4;color:#333;margin:0 0 12px;text-transform:none}.hw-spec-list{list-style:disc;margin:0 0 26px;padding:0 0 0 20px}.hw-spec-list li{font-family:Roboto,Helvetica,Arial,sans-serif;font-weight:400;font-size:16px;line-height:1.9;color:#333}.hw-spec-desc{font-family:Roboto,Helvetica,Arial,sans-serif;font-weight:400;font-size:15px;line-height:1.8;color:#333;margin:0 0 24px}
.hw-btn-dark{font-family:Poppins,Helvetica,Arial,sans-serif;font-weight:600;font-size:14px;line-height:1.2;letter-spacing:.4px;text-transform:uppercase;color:#fff;background:#333;padding:18px 26px;display:inline-block;text-decoration:none}.hw-btnstack .hw-btn-dark{margin-bottom:2px}.hw-btnstack .hw-btn-red{margin-top:2px}
.hw-gallery-sec{padding:44px 0}.hw-gallery{display:grid;grid-template-columns:repeat(3,1fr);gap:40px;background:#e8e8e8;padding:30px;align-items:start}.hw-gallery img{width:100%;height:auto;object-fit:cover;display:block;box-shadow:0 8px 18px rgba(0,0,0,.16)}
.hw-footer-bar{background:var(--red);color:#fff;font-family:"Open Sans",Helvetica,Arial,sans-serif;font-size:13px;line-height:1.5;text-align:center;padding:13px 20px}.hw-footer-bar a{color:#fff;text-decoration:underline}
@media (max-width:767px){.hw-nav{display:none}.hw-burger{display:flex}body.hw-page{padding-top:149px}.hw-topbar{height:auto;min-height:85px;padding:9px 0}.hw-topbar .hw-wrap{flex-direction:row;flex-wrap:wrap;justify-content:center;gap:4px 14px;text-align:center;padding:0 16px}.hw-topbar .hw-phone,.hw-topbar .hw-email{justify-content:center}.hw-mainbar{height:64px}.hw-mainbar .hw-wrap{align-items:center}.hw-logo{align-self:center}.hw-logo img{height:35px}.hw-cat-title{font-size:34px;line-height:38px}.hw-cat-sub{font-size:24px}.hw-cat-intro{font-size:18px;line-height:1.6}.hw-band-title{font-size:28px;line-height:32px}.hw-band-cols{grid-template-columns:1fr;max-width:360px;margin:0 auto;gap:0}.hw-cat-grid{grid-template-columns:1fr;row-gap:40px;max-width:460px;margin:0 auto}.hw-redband-title{font-size:28px}.hw-redband-text{font-size:18px}.hw-split{grid-template-columns:1fr}.hw-split-img{min-height:260px}.hw-split-body,.hw-split-body.wide{padding:36px 24px}.hw-spec-h{font-size:24px}.hw-gallery{grid-template-columns:1fr;gap:24px}.hw-storehero h2{font-size:34px}}</style>
<link rel="stylesheet" href="/wp-content/hw-fonts/hw-fonts.css" media="print" onload="this.media='all';this.onload=null">
<link rel="stylesheet" href="<?php echo get_stylesheet_directory_uri(); ?>/assets/css/category.css?v=<?php echo @filemtime(get_stylesheet_directory().'/assets/css/category.css'); ?>" media="print" onload="this.media='all';this.onload=null">
<noscript><link rel="stylesheet" href="/wp-content/hw-fonts/hw-fonts.css"><link rel="stylesheet" href="<?php echo get_stylesheet_directory_uri(); ?>/assets/css/category.css"></noscript>
<?php wp_head(); ?>
